# Specify default config file
#
# Below is a bloated example of a config file.
#
#spec-kit:
#  - constitution:
#      path: "CONSTITUTION.md"
#      documents:
#        - path: "docs/architecture.md"
#          context: "Documents the architecture of the project and should be considered a primary source of truth."
#        - path: "docs/ui-architecture.md"
#          context: "Documents the UI architecture of the project and should be considered a primary source of truth."
#  - specify:
#      documents:
#        - path: "docs/prd.md"
#          context: "Documents the product requirements and should be considered a primary source of truth."
#        - path: "docs/front-end-spec.md"
#          context: "Documents the front-end specifications and should be considered a primary source of truth."
#  - plan:
#      technical_context:
#        - "**Coding Standards**: [NEEDS CLARIFICATION]"
#      additional_research:
#        - "Analyse the architecture documents and prepare a summary of the relevant sections as they relate to the implementation of the plan."
#      documents:
#        - path: "docs/architecture.md"
#          context: "Documents the architecture of the project and should be considered a primary source of truth."
#        - path: "docs/ui-architecture.md"
#          context: "Documents the UI architecture of the project and should be considered a primary source of truth."
#        - path: "docs/front-end-spec.md"
#          context: "Documents the front-end specifications and should be considered a primary source of truth."
#  - tasks:
#      documents:
#        - path: "docs/architecture.md"
#          context: "Documents the architecture of the project and should be considered a primary source of truth."
#        - path: "docs/ui-architecture.md"
#          context: "Documents the UI architecture of the project and should be considered a primary source of truth."
#        - path: "docs/front-end-spec.md"
#          context: "Documents the front-end specifications and should be considered a primary source of truth."
#  - implement:
#      documents:
#        - path: "docs/work-flow.md"
#          context: "Documents the implementation work-flow for the project and should be considered a primary source of truth."

spec-kit:
  - constitution:
      path: "/memory/constitution.md"